defaults:
  - /base_configs/dataLoader_config.yaml@_here_ 
  - _self_
# make sure _self_ is in the end as it means to inherent last from this file meaning overwriting the inhereted values if needed

global_batch_size: 32
# add more as required
