defaults:
  - /base_configs/optimizer_config.yaml@_here_ 
  - _self_
# make sure _self_ is in the end as it means to inherent last from this file meaning overwriting the inhereted values if needed

#CHANGE THE ARGUMENTS BELOW
lr: 0.002
# add more as required
