config_path_prefix: /

base_model: EKA_DeepSeekV3Model

base_model_config: EKA_DeepSeekV3Config
base_model_configuartion_path: base_model_config.yaml

dataLoader_config_path: dataLoader_config.yaml
optimizer_config_path: optimizer_config.yaml
trainer_config_path: trainer_config.yaml
logger_config_path: logger_config.yaml